class_name Constants

enum Options { SCENE, 
	WAVES_X, WAVES_Y, WAVES_Z, 
	CLOUD_X, CLOUD_Y, CLOUD_Z, CLOUD_W,
	NOISE_SCALE_X, NOISE_SCALE_Y, NOISE_SCALE_Z, NOISE_SCALE_W,
	GALAXY_ROTATE, TRAFFIC, MUSIC, SFX
}
